apiVersion: v1
name: harbor-scanner-trivy
version: 0.33.2
appVersion: 0.33.2
description: Harbor scanner adapter for Trivy
keywords:
  - scanner
  - harbor
  - vulnerability
sources:
- https://github.com/goharbor/harbor-scanner-trivy
